version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: test
          command: npm i && npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test