version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: test
          command: npm i && npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
